#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#Python Template for ES2B4 Assignment

#Name: PABLO NAVAJAS HELGUERO
#ID : 1604648
#Assignment: assignment_a3_2.py
#Section: A3-2

### My code:

#Import the time library to ensure that the program works as a count down clock
import time

#Set the input to False to use a boolean condition in the loop
InputN = False

#Create a loop that we can exit in case of Error
while InputN == False:
    
    #Ask the user to enter a starting value for the count down
    InputN = input("Introduce starting value: ")
    
    #Check if the input is a number
    try:
        StartN = int(InputN)
        
    #If it is not a number, ask the user to enter a valid Number and close program
    except:
        print("You need to introduce a valid number. ")
        break
    
    #If the Input is a positive number:
    while StartN>0:
        
        #Print the values in decreasing order with a gap of 1 second between each
        print(StartN)
        StartN = StartN-1
        time.sleep(1)
        
    #If the value is zero, print "Finish!"
    if StartN==0:
        print("Finish!")
        
    #If the Input is a negative number, inform the user
    else:
        print("That's not a valid input. ")
        
    #Close the program 
    break
    
